SELECT 
    UTM_Norte, UTM_Este,
    MAX(Huso) AS Huso, MAX(Region) AS Region, MAX(Provincia) AS Provincia, MAX(Comuna) AS Comuna,
    MAX(Cod_Cuenca) AS Cod_Cuenca, MAX(Nom_Cuenca) AS Nom_Cuenca, MAX(Cod_Subcuenca) AS Cod_Subcuenca, MAX(Nom_Subcuenca) AS Nom_Subcuenca,
    MAX(Cod_Subsubcuenca) AS Cod_Subsubcuenca, MAX(Nom_Subsubcuenca) AS Nom_Subsubcuenca,
    AVG(CAST(Caudal AS FLOAT)) AS caudal_promedio, MIN(CAST(Caudal AS FLOAT)) AS caudal_minimo, MAX(CAST(Caudal AS FLOAT)) AS caudal_maximo, STDEV(CAST(Caudal AS FLOAT)) AS caudal_desviacion_estandar,
    COUNT(*) AS n_mediciones, MAX(codigo) AS codigo,
    MAX(COD_SECTOR_SHA) AS COD_SECTOR_SHA, MAX(SECTOR_SHA) AS SECTOR_SHA, MAX(CAST(APR AS INT)) AS APR,
    MAX(ID_JUNTA) AS ID_JUNTA, MAX(CAST(PARTE_JUNTA AS INT)) AS PARTE_JUNTA, MAX(CAST(REPRESENTA_JUNTA AS INT)) AS REPRESENTA_JUNTA,
    MAX(CANAL_TRANSMISION) AS CANAL_TRANSMISION,
    MAX(TIPO_DERECHO) AS TIPO_DERECHO,
    MAX(VOLUMEN_ANUAL) AS VOLUMEN_ANUAL,
    MAX(CAUDAL_ENERO) AS CAUDAL_ENERO, MAX(CAUDAL_FEBRERO) AS CAUDAL_FEBRERO, MAX(CAUDAL_MARZO) AS CAUDAL_MARZO,
    MAX(CAUDAL_ABRIL) AS CAUDAL_ABRIL, MAX(CAUDAL_MAYO) AS CAUDAL_MAYO, MAX(CAUDAL_JUNIO) AS CAUDAL_JUNIO,
    MAX(CAUDAL_JULIO) AS CAUDAL_JULIO, MAX(CAUDAL_AGOSTO) AS CAUDAL_AGOSTO, MAX(CAUDAL_SEPTIEMBRE) AS CAUDAL_SEPTIEMBRE,
    MAX(CAUDAL_OCTUBRE) AS CAUDAL_OCTUBRE, MAX(CAUDAL_NOVIEMBRE) AS CAUDAL_NOVIEMBRE, MAX(CAUDAL_DICIEMBRE) AS CAUDAL_DICIEMBRE
INTO dw.Puntos_Mapa
FROM dw.Mediciones_full
WHERE UTM_Norte IS NOT NULL AND UTM_Este IS NOT NULL
GROUP BY UTM_Norte, UTM_Este;

GO

SELECT 
    MAX(COD_CUENCA) AS COD_CUENCA, MAX(NOM_CUENCA) AS NOM_CUENCA,
    MAX(COD_SUBCUENCA) AS COD_SUBCUENCA, MAX(NOM_SUBCUENCA) AS NOM_SUBCUENCA,
    MAX(COD_SUBSUBCUENCA) AS COD_SUBSUBCUENCA, MAX(NOM_SUBSUBCUENCA) AS NOM_SUBSUBCUENCA,
    UTM_NORTE, UTM_ESTE, CAST(FECHA_MEDICION AS DATE) AS FECHA_MEDICION,
    AVG(CAST(CAUDAL AS FLOAT)) AS CAUDAL,
    AVG(CAST(ALTURA_LIMNIMETRICA AS FLOAT)) AS ALTURA_LIMNIMETRICA,
    AVG(CAST(NIVEL_FREATICO AS FLOAT)) AS NIVEL_FREATICO,
    MAX(TOTALIZADOR) AS TOTALIZADOR
INTO dw.Series_Tiempo
FROM dw.Mediciones_full
WHERE UTM_NORTE IS NOT NULL AND UTM_ESTE IS NOT NULL AND FECHA_MEDICION IS NOT NULL
GROUP BY UTM_NORTE, UTM_ESTE, CAST(FECHA_MEDICION AS DATE);

GO